import {
  Box,
  Flex,
  FormControl,
  FormLabel,
  Heading,
  Image,
  Select,
  VStack,
} from "@chakra-ui/react";
import { useFormik } from "formik";

import Navbar from "../components/Navbar";
import findDoctorImg from "../assets/images/find-doctor.svg";

const FindDoctor = () => {
  const formik = useFormik({
    initialValues: {
      specialization: "",
      wilaya: "",
    },
    onSubmit: (values) => {
      alert(JSON.stringify(values, null, 2));
    },
  });

  const specialities = [
    "Addictologie",
    "Aide Soignant(e)",
    "Algologie",
    "Allergologie",
    "Anapath",
    "Andrologie",
    "Anesthésie - Réanimation",
    "Assistance médicale",
    "Association dans le médical",
    "Audioprothèse",
    "Auriculothérapie",
    "Biochimie",
    "Biologie",
    "Brûlologie",
    "Cabinet de groupe",
    "Cancérologie",
    "Cardio-Respiratoire",
    "Cardiologie",
    "Centre d'Audiométrie et de Prothèse Auditive",
    "Centre d'Imagerie Médicale",
    "Centre de dépistage Coronavirus",
    "Centre de diagnostique médical",
    "Centre de soins corporels",
    "Centre vaccination Covid-19",
    "Chirurgie Cardiovasculaire",
    "Chirurgie Cervico Faciale",
    "Chirurgie Cervico, Maxillo-Faciale, Réparatrice et Esthétique",
    "Chirurgie Coelioscopique",
    "Chirurgie Digestive",
    "Chirurgie Endocrinienne",
    "Chirurgie Esthétique",
    "Chirurgie Générale",
    "Chirurgie Gynécologique",
    "Chirurgie Orthopédique traumatologique",
    "Chirurgie Pédiatrique",
    "Chirurgie Thoracique",
    "Chirurgie Urologique",
    "Chirurgie Vasculaire",
    "Clinicienne d'enfants",
    "Cytopathologie",
    "Dentiste",
    "Dermatologie",
    "Diabétologie",
    "Endocrinologie",
    "Endocrinologie-Diabétologie",
    "Endodontie",
    "Epidémiologie",
    "Gastro-entérologie",
    "Gynécologie",
    "Gynécologie obstétrique",
    "Hématologie",
    "Hépato-Gastro-Entérologie",
    "Hépatologie",
    "Histologie",
    "Immunologie",
    "Implantologie",
    "Infectiologie",
    "Infirmier - Infirmière",
    "Kinesithérapie",
    "Laboratoire d'analyses médicales",
    "Laboratoire d'anatomie et cytologie pathologique",
    "Maladies des os et articulations",
    "Médecin assermenté",
    "Médecine d'urgence",
    "Médecine de travail",
    "Médecine dentaire spécialisé",
    "Médecine du sommeil",
    "Médecine du sport",
    "Médecine esthétique",
    "Médecine générale",
    "Médecine génétique",
    "Médecine interne",
    "Médecine légale",
    "Médecine néonatale",
    "Médecine nucléaire",
    "Médecine physique",
    "Mésothérapie",
    "Néphrologie",
    "Neurochirurgie",
    "Neurologie",
    "Neuropédiatrie",
    "Neurophysiologie",
    "Neuropsychiatrie",
    "Neuropsychologie",
    "Nutrition",
    "Odotologie conservatrice",
    "Omnipraticien",
    "Oncologie",
    "Ophtalmologie",
    "Opticien",
    "ORL (Oto-rhino-laryngologie)",
    "Orthodontie",
    "Orthopédie Dento-Faciale",
    "Orthopédie pédiatrique",
    "Orthophonie",
    "Orthoptie",
    "Ostéopathie",
    "Parapsychologie",
    "Parasitologie",
    "Parodontologie",
    "Patho Bucco Dentaire",
    "Pathologie et chirurgie buccale",
    "Pédiatrie",
    "Pédodontie",
    "Pédopsychiatrie",
    "Pharmacie",
    "Physiologie",
    "PMI (Protection Maternelle et Infantile)",
    "Pneumo-allergologie pédiatrique",
    "Pneumo-phtisiologie",
    "Podologie",
    "Prothèse dentaire",
    "Psychiatrie",
    "Psychologie",
    "Psychopédagogie",
    "Psychothérapie",
    "Réanimation",
    "Rééducation Fonctionnelle",
    "Rhumatologie",
    "Sage femme",
    "Sénologie",
    "Sexologie",
    "Tourisme Médical",
    "Toxicologie",
    "Vénéréologie",
    "Vente matériels & Consommables médicales",
    "Vétérinaire",
  ];

  const optionsText = [
  "Addiction Medicine",
  "Nursing Assistant",
  "Algology",
  "Allergology",
  "Anatomical Pathology",
  "Andrology",
  "Anesthesia - Resuscitation",
  "Medical Assistance",
  "Association in Medicine",
  "Audioprosthesis",
  "Auriculotherapy",
  "Biochemistry",
  "Biology",
  "Burn Medicine",
  "Group Practice",
  "Oncology",
  "Cardio-Respiratory",
  "Cardiology",
  "Audiometry and Hearing Aid Center",
  "Medical Imaging Center",
  "Coronavirus Screening Center",
  "Medical Diagnostic Center",
  "Body Care Center",
  "Covid-19 Vaccination Center",
  "Cardiovascular Surgery",
  "Cervico Facial Surgery",
  "Cervico-Maxillo-Facial, Reconstructive, and Aesthetic Surgery",
  "Laparoscopic Surgery",
  "Digestive Surgery",
  "Endocrine Surgery",
  "Aesthetic Surgery",
  "General Surgery",
  "Gynecological Surgery",
  "Orthopedic Traumatology Surgery",
  "Pediatric Surgery",
  "Thoracic Surgery",
  "Urological Surgery",
  "Vascular Surgery",
  "Children's Clinician",
  "Cytopathology",
  "Dentist",
  "Dermatology",
  "Diabetology",
  "Endocrinology",
  "Endocrinology-Diabetology",
  "Endodontics",
  "Epidemiology",
  "Gastroenterology",
  "Gynecology",
  "Obstetric Gynecology",
  "Hematology",
  "Hepato-Gastro-Enterology",
  "Hepatology",
  "Histology",
  "Immunology",
  "Implantology",
  "Infectiology",
  "Nurse",
  "Physiotherapy",
  "Medical Laboratory",
  "Anatomy and Pathological Cytology Laboratory",
  "Bone and Joint Diseases",
  "Sworn Doctor",
  "Emergency Medicine",
  "Occupational Medicine",
  "Specialized Dental Medicine",
  "Sleep Medicine",
  "Sports Medicine",
  "Aesthetic Medicine",
  "General Medicine",
  "Medical Genetics",
  "Internal Medicine",
  "Legal Medicine",
  "Neonatal Medicine",
  "Nuclear Medicine",
  "Physical Medicine",
  "Mesotherapy",
  "Nephrology",
  "Neurosurgery",
  "Neurology",
  "Neuropediatrics",
  "Neurophysiology",
  "Neuropsychiatry",
  "Neuropsychology",
  "Nutrition",
  "Conservative Otology",
  "General Practitioner",
  "Oncology",
  "Ophthalmology",
  "Optician",
  "ENT (Oto-rhino-laryngology)",
  "Orthodontics",
  "Orthopedic Dento-Facial",
  "Pediatric Orthopedics",
  "Speech Therapy",
  "Orthoptics",
  "Osteopathy",
  "Parapsychology",
  "Parasitology",
  "Periodontology",
  "Bucco-Dental Pathology",
  "Oral Pathology and Surgery",
  "Pediatrics",
  "Pedodontics",
  "Child Psychiatry",
  "Pharmacy",
  "Physiology",
  "Maternal and Child Protection",
  "Pediatric Pneumo-Allergology",
  "Pneumo-Phthisiology",
  "Podiatry",
  "Dental Prosthetics",
  "Psychiatry",
  "Psychology",
  "Psychopedagogy",
  "Psychotherapy",
  "Resuscitation",
  "Functional Rehabilitation",
  "Rheumatology",
  "Midwife",
  "Senology",
  "Sexology",
  "Medical Tourism",
  "Toxicology",
  "Venereology",
  "Sale of Medical Equipment & Consumables",
  "Veterinarian"
];


  return (
    <Flex>
      <Navbar />

      <Flex
        width={"100%"}
        mt={"150px"}
        mx={{ base: "20px", md: "50px", xl: "100px", "2xl": "150px" }}
        justifyContent={"space-between"}
      >
        {/* Form */}
        <Box width={"40%"}>
          <Heading mb={"50px"}>
            Rendez-vous en ligne chez un établissement de santé
          </Heading>
          <form onSubmit={formik.handleSubmit}>
            <VStack>
              <FormControl>
                <FormLabel>Specialization</FormLabel>
                <Select placeholder="Select Specialization">
                  {specialities.map((speciality) => (
                    <option value={speciality}>{speciality}</option>
                  ))}
                </Select>
              </FormControl>
            </VStack>
          </form>
        </Box>

        <Image
          width={{
            base: "250px",
            sm: "300px",
            md: "45%",
            "2xl": "650px",
          }}
          src={findDoctorImg}
        ></Image>
      </Flex>
    </Flex>
  );
};

export default FindDoctor;
